version: 2

sources:
  - name: source_adventure
    description: Fonte de dados Adventureworks
    schema: Adventureworks
    tables:

        - name: production_product
          description: Tabela com informações dos produtos.
          columns:

            - name: productid
              description: Chave primária da tabela de produtos
            - name: productsubcategoryid
              description: Subcategoria do Produto / Chave estrangeira
            - name: productmodelid
              description: Nome do produto
            - name: productnumber
              description: Numero de registro do produto
            - name: color
              description: Cor do produto
            - name: safetystocklevel
              description: Nivel seguro de estoque do produto
            - name: standardcost
              description: Custo padrão
            - name: listprice
              description: Custo de venda
            - name: daystomanufacture
              description: Tempo de fabricação do produto
            - name: productline
              description: Linha do Produto
            - name: class
              description: Classe do Produto
            - name: style
              description: Estilo do Produto
            - name: sellstartdate
              description: Data início da Venda
            - name: sellenddate
              description: Data Fim da Venda

        - name: sales_salesorderdetail
          description: Tabela com informações detalhadas sobre o pedido de venda
          columns:

            - name: salesorderid
              description: Chave primária para a tabela de detalhes do pedido de venda e chave estrangeira da tabela com informações do cabeçalho do pedido de venda
            - name: salesorderdetailid
              description: Chave primária da tabela de detalhes do pedido de venda
            - name: productid
              description: Chave estrangeira da tabela de produtos
            - name: orderqty
              description: Quantidade de pedidos
            - name: unitprice
              description: Preço unitario do produto
            - name: unitpricediscount
              description: Desconto por preço unitário

        - name: sales_salesorderheader
          description: Tabela com informações do cabeçalho do pedido de venda
          columns:

            - name: salesorderid
              description: Chave primaria e estrangeira da tabela de detalhes do pedido de venda
              tests:
                - unique
                - not null
            - name: orderdate
              description: Data do pedido da venda
            - name: duedate
              description: Data em que o pedido é devido ao cliente				
            - name: shipdate
              description: Informação de data que o pedido é enviado ao cliente
            - name: status
              description: Informação sobre status atual do pedido (1= In process, 2= Approved, 3= BackOrdered, 4= Rejected, 5= Shipped, 6= Cancelled)
            - name: customerid
              description: chave estrangeira - id do cliente
            - name: salespersonid
              description: chave estrangeira - id do vendedor
            - name: territoryid
              description: chave estrangeira - id territorio de venda  
            - name: creditcardid
              description: Id - Informações de cartão de crédito			
            - name: orderdate
              description: Informação de data que o pedido de venda foi criado.				
            - name: shiptoaddressid
              description: Chave estrangeira - Id do endereço de envio do pedido.
            - name: shipmethodid
              description: Chave estrangeira - Id do metodo de envio.	
            - name: subtotal
              description: Informação referente ao subtotal, desconsiderando imposto e frete				
            - name: taxamt
              description: Valor de imposto
            - name: freight
              description: valor de frete 			
            - name: totaldue
              description: Total devido, considerando valor de imposto e frete							

        - name: sales_salesreason
          description: Tabela com informações do motivo da venda
          columns:

            - name: salesreasonid
              description: Chave primaria da tabela de motivos de venda
              tests:
                - unique
                - not null  
            - name: name
              description: motivo da venda
            - name: reasontype
              description: Categoria a qual se enquadra o motivo
        
        - name: sales_creditcard
          description: Tabela com informações do tipo de cartao
          columns:

            - name: creditcardid
              description: Chave primaria da tabela de cartao de credito
              tests:
                - unique
                - not null  
            - name: cardtype
              description: Tipo de cartao de credito
          
        - name: sales_salesorderheadersalesreason
          description: Tabela com informações de ordem de pedido venda com motivo de venda
          columns:

            - name: salesorderid
              description: Chave primaria e estrangeira da ordem do pedido de venda
              tests:
                - unique
                - not null  
            - name: salesreasonid
              description: Chave primaria e estrangeira para identificação do motivo de venda
            
        - name: person_person
          description: Tabela com informações de pessoas de negocio
          columns:

            - name: businessentityid
              description: Chave primaria da tabela de pessoal
              tests:
                - unique
                - not null  
            - name: persontype
              description: Tipo de pessoal (SC=Store Contact; IN=Individual(retail) customer; SP=Sales Person; EM=Employee(non-sales); VC=Vendor Contact; GC=General Contact)  
            - name: title
              description: Titulação do nome
            - name: firstname
              description: Primeiro nome
            - name: middlename
              description: Nome do meio
            - name: lastname
              description: ultimo nome
            - name: suffix
              description: sufixo do ultimo nome - quanto houver

        - name: sales_customer
          description: Tabela com informações dos clientes
          columns:

            - name: customerid
              description: Chave primaria da tabela de cliente
              tests:
                - unique
                - not null  
            - name: personid
              description: Chave estrangeira para a tabela informações pessoais 
            - name: storeid
              description: Chave estrangeira para a tabela com informações sobre a loja
            - name: territoryid 
              description: chave estrangeira para a tabela de território  

        - name: person_address
          description: Tabela com informações de endereco
          columns:

            - name: addressid
              description: Chave primaria da tabela de endereco
              tests:
                - unique
                - not null  
            - name: addressline1
              description: Informações sobre o endereço 
            - name: addressline2
              description: Informações complementares do endereço 
            - name: city
              description: Cidade correspondente do endereço
            - name: stateprovinceid
              description: chave estrangeira da tabela estado
            - name: spatiallocation
              description: informações sobre a localicação espacial  

        - name: person_stateprovince
          description: Tabela com informações de cidade
          columns:

            - name: stateprovinceid
              description: Chave primaria da tabela estado
              tests:
                - unique
                - not null  
            - name: stateprovincecode
              description: Código do estado
            - name: countryregioncode
              description: Código da região estado - país   
            - name: name
              description: Nome do Estado 
            - name: territoryid
              description: chave estrangeira da tabela territorio 

        - name: person_countryregion
          description: Tabela com informações de Estado - País
          columns:

            - name: countryregioncode
              description: Chave primaria / Código do Estado - País
              tests:
                - unique
                - not null  
            - name: name
              description: Nome do Estado-País

            

            
            
            
            

